* Fixed imvipdlsvr.conf should not have local path for keystore.

diff --git a/bin/repo b/bin/repo
--- a/bin/repo
+++ b/bin/repo
@@ -5,16 +5,19 @@
 # Exit Code
 # 0     Execution completed successfully.
 # 1	Warning!
-#255	Error!
+# 255	Error!
 #
+
+# uncomment the following to enable debug output.
 ###set +x
-##
+
 ##
 ##
 ##
 ######
 version=$2
 export version
+
 ##
 ##
 ##
@@ -29,25 +32,31 @@ BASE_DIR=$(dirname $0)/..
 . $LIB_DIR/core.android || exit 255 
 . $LIB_DIR/log || exit 255 
 
-#exce update 1.0.0 android
+
+
 #input order format
 if [ $(whoami) != "root" ];then
-	echo "Warning:you is not root user"
-	exit 1;
-fi 
+	echo "Warning: You must be root to perform this operation"
+	exit 1
+fi
+# display help message and exit with error.
 if [ $# == 0 ];then 
 	echo "usage:  repo <command> [--version] [--program] " 
-	echo "The most commonly used repo commands are" 
-	echo "   deploy: download program version in a special dir" 
-	echo "   for example: ./repo deploy 1.0.0 android " 
+	echo 
+	echo "The most commonly used commands:"
+	echo "  deploy    deploy specified client application to this server" 
+	echo "            syntax:"
+	echo "             deploy <app-version> <platform>"
+	echo "            example:"
+	echo "             repo deploy 1.0.2 android"
 	exit 255
 fi
-if [ $# == 1 ] || [ $# == 2 ] && [ $1 == "deploy" ];then
+if [ $# == 1 ] || [ $# == 2 ] && [ $1 == "deploy" ]; then
 	echo "error: this command is not deploy or input command incorrect"
 	echo "Try './repo'"
-	exit 255
+	exit 256
 fi
-if [ $# == 1 ] || [ $# == 2 ] && [ $1 != "deploy" ];then
+if [ $# == 1 ] || [ $# == 2 ] && [ $1 != "deploy" ]; then
 	echo "error: this command is not deploy or input command incorrect"
 	echo "Try './repo'"
 	exit 255
@@ -69,40 +78,42 @@ if [ $# == 3 ] && [ $1 == "deploy" ];then
 	##	
 	##test android-1.0.*.apk exit?
 	if [ -e $(bulid_android_srcpkg_path) ];then
-	echo "Warning:$3-$2.apk is exist!"
-	exit 1
+		echo "Warning:$3-$2.apk is exist!"
+		exit 1
 	fi	
 	##not exit download android-1.0.0.apk
         tmp_dir=$(mktemp -d  $BASE_DIR/tmp.XXXXXX)
 	wget -P $tmp_dir $androidurl 
 	#download success move to DATA_DIR/src_pkg
-	if [ $? != 0 ];then
-	echo "Warning:there is not the correct version program!"
-	echo  "Warning:DOWNLOAD IS FAILURE!"
-	exit 1
+	if [ $? != 0 ]; then
+		echo "Warning:there is not the correct version program!"
+		echo  "Warning:DOWNLOAD IS FAILURE!"
+		exit 1
 	fi
 	if [ ! -d $data_src_dir ];then
-	mkdir $data_src_dir
-	sudo chown www-data:www-data $data_src_dir
+		mkdir $data_src_dir
+		sudo chown www-data:www-data $data_src_dir
 	fi
 	mv $tmp_dir/$3-$2.apk $data_src_dir
 	if [ $? != 0 ];then
-	echo "Warning:Moving havn't successful!"
-	sudo rm -r $tmp_dir
-	exit 1
+		echo "Warning:Moving havn't successful!"
+		sudo rm -r $tmp_dir
+		exit 2
 	fi
 	sudo rm -r $tmp_dir
 	#write verison to android
 	if [ ! -f $data_lastversion_dir ];then 
-	touch $data_lastversion_dir
-	sudo chown www-data:www-data $data_lastversion_dir
-	echo $2 > $data_lastversion_dir
-        echo "DOWNLOAD IS SUCCESSFUL!"
-	exit 0
+		touch $data_lastversion_dir
+		sudo chown www-data:www-data $data_lastversion_dir
+		echo $2 > $data_lastversion_dir
+		echo "DOWNLOAD IS SUCCESSFUL!"
+		exit 0
 	fi
 	sudo chown www-data:www-data $data_lastversion_dir
 	echo $2 > $data_lastversion_dir
 	echo "DOWNLOAD IS SUCCESSFUL!"
 	exit 0
 fi
-	
+
+echo "Invalid number of arguments"
+exit 1
